version: "3.2"
services:
  frontend:
    build: ./client
    volumes:
      - ./client:/app
      - ./client/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start

  backend:
    build: ./
    command: node server.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet    

